apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-read-role
  labels:
    app: super-app
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-reader-rolebinding
  labels:
    app: super-app
subjects:
  - kind: ServiceAccount
    name: api-reader
#  namespace: default
roleRef:
  kind: Role
  name: api-read-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-reader
  labels:
    app: super-app