apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-read-role
  labels:
    app: true-feature-flag
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-reader-rolebinding
  labels:
    app: true-feature-flag
subjects:
  - kind: ServiceAccount
    name: api-reader
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: api-read-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-reader
  labels:
    app: true-feature-flag