apiVersion: v1
kind: Service
metadata:
  name: feature-flag-test-app
  labels:
    app: true-feature-flag
spec:
  ports:
    - port: 8500
      targetPort: 8500
      name: http
  selector:
    app: feature-flag-test-app