# Default values for ff-portal-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  tag: latest

pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

config:
  path: /etc/ff/config

serviceAccount:
  create: true
  annotations: { }
  name: ""

recreationEnabled: false

hostlogs: true

ingress:
  class: ns-ingress

#----------------------------------------------------------
resourceRequests:
  small:
    memory: "356Mi"
    cpu: "200m"

resourceLimits:
  small:
    memory: "512Mi"
    cpu: "1500m"
#----------------------------------------------------------

actuatorPath: /test-app/actuator/health

#----------------------------------------------------------
livenessProbeTime:
  small:
    initialDelaySeconds: 600

  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

#----------------------------------------------------------
readinessProbeTime:
  small:
    initialDelaySeconds: 10

  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5
#----------------------------------------------------------

storage:
  printForms:
    class: sas
    size: 1Gi
