name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v5.1.0
      id: generate-version
      with:
        tag_prefix: "v"
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 
      with:
        arguments: clean build
    - name: Build the Docker image
      run: docker build . --file Dockerfile -t ghcr.io/true-engineering/feature-flag-test-app:$SEM_VERSION --build-arg GITHUB_TOKEN=$GITHUB_TOKEN
      env:
        SEM_VERSION: ${{ steps.generate-version.outputs.version }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push
      run: docker push ghcr.io/true-engineering/feature-flag-test-app:$SEM_VERSION
      env:
        SEM_VERSION: ${{ steps.generate-version.outputs.version }}
    - name: Create tag and push
      run: git tag v${{ steps.generate-version.outputs.version }} && git push --tags || echo "tag already exist"
